export enum TrackingMetric {
  WEIGHT = 'WEIGHT',
  REPS = 'REPS',
  DURATION = 'DURATION',
  DISTANCE = 'DISTANCE',
  TIME = 'TIME',
  RPE = 'RPE',
  ASSISTANCE_WEIGHT = 'ASSISTANCE_WEIGHT',
  BODY_WEIGHT = 'BODY_WEIGHT',
  CALORIES = 'CALORIES',
}
